default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  min_messages: WARNING
  pool: 5
  timeout: 5000
  # username: pguser
  # password: pgpass

development:
  <<: *default
  database: studmuffin-dev

test:
  <<: *default
  database: studmuffin-test

production:
  <<: *default
  database: studmuffin-prod
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %
